### PR TITLE
Re-package for composer

### PR DESCRIPTION
**Pull request by thoaionline**
This PR allows the plugin to be included directly into another project with composer.

After merging, please tag as 2.0.0 as this is not BC.

### CODE REVIEW

**Comment by thoaionline** [comment]
Can you merge this @MartyWallace?

**Comment by thoaionline** [comment]
Can you add a new tag too?

**Comment by MartyWallace** [comment]
Thanks @wiso1234

**Comment by wiso1234** [comment]
Hi Thoay,

We've released an alpha version 2 of Art Vandelay. See what you think, if
you have time have a think about adding the CLI stuff for the new features.

cheers

Andrew

**Pull request merged**
